Repository cognitedata/cognite-sdk-python-experimental, pull requests merged in 2021-03, with the labels that each got.

#158 Fix plot extractor
  CHANGELOG.md
  cognite/experimental/_api/plot_extraction.py
  pyproject.toml
Labels: auto-merge, auto-update

#159 Fix plot doc
  cognite/experimental/_api/plot_extraction.py
Labels: auto-merge, auto-update

#160 Fix missing client from _load in func.list and schedules.list
  CHANGELOG.md
  cognite/experimental/_api/functions.py
  pyproject.toml
Labels: auto-merge, bug

#161 Update annotations
  CHANGELOG.md
  cognite/experimental/_api/annotations.py
  cognite/experimental/data_classes/annotations.py
  docs/source/cognite.rst
  pyproject.toml
  tests/tests_integration/test_contextualization/test_annotations.py
Labels: auto-merge
